export const authActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  USER_SIGN_IN_START: "USER_SIGN_IN_START",
  USER_SIGN_UP_START: "USER_SIGN_UP_START",
  USER_SIGN_IN_UP_SUCCESS: "USER_SIGN_IN_UP_SUCCESS",
  USER_SIGN_IN_UP_FAILURE: "USER_SIGN_IN_UP_FAILURE",
  USER_SIGN_OUT_START: "USER_SIGN_OUT_START",
  USER_SIGN_OUT_SUCCESS: "USER_SIGN_OUT_SUCCESS",
  USER_SIGN_OUT_FAILURE: "USER_SIGN_OUT_FAILURE",
};
